
defaults:
  - _self_
  - data: null
  - train: null
  - model: null
  - trainer: default
  - extras: default
  - callbacks: default
  - paths: default
  - logger: tensorboard
  - hydra: default
  - experiment: ???
task_name: ???

train: true
test: true

tags: ["dev"]

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null
